# Generated by Django 4.0.1 on 2022-02-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
