# Generated by Django 4.0.1 on 2022-02-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_book_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='book',
        ),
    ]
