# Generated by Django 4.0.1 on 2022-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_review_rate_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
