# Generated by Django 4.0.1 on 2022-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_book_rating_delete_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_destroy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='destroy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='userdestroy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
