# Generated by Django 4.0.1 on 2022-02-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_book_date_destroy_book_destroy_book_userdestroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='userdestroy',
            new_name='user_destroy',
        ),
    ]
